Repository SreenivasDheeraj/Python-Beginners, pull requests merged in 2020-10, with the labels that each got.

#1 Solved problem 22
  Solutions/22.py
Labels: good first issue

#6 Added the solution of 9th program
  Solutions/9.py
Labels: hacktoberfest-accepted

#13 solution to 3, 5, 12, 25 and 27
  Solutions/12.py
  Solutions/25.py
  Solutions/27.py
  Solutions/3.py
  Solutions/5.py
Labels: hacktoberfest-accepted

#10 Added the solution of 1st program
  hello world.py
Labels: hacktoberfest-accepted

#9 Completed program 2
  Solutions/Program2.py
  Solutions/Program3.py
Labels: hacktoberfest-accepted

#11 added solution for #18
  Solutions/18.py
Labels: hacktoberfest-accepted

#12 Solution for question 3: Add two integers
  Solutions/3.py
Labels: hacktoberfest-accepted

#16 odd or even program
  3.py
  oddeven.py
Labels: hacktoberfest-accepted

#15 6th solution
  Solutions/6
Labels: good first issue, hacktoberfest-accepted

#20 transpose of a matrix
  Solutions/transpose of matrix.py
Labels: hacktoberfest-accepted

#21 General multiplication table
  Solutions/general multiplication table.py
Labels: hacktoberfest-accepted

#22 30th solution
  20.py
  Solutions/30.py
  Solutions/4.py
Labels: hacktoberfest-accepted

#23 solution for 15 Q added
  Solutions/15.py
Labels: hacktoberfest-accepted

#24 Find power of a number
  Solutions/find power of a number.py
Labels: hacktoberfest-accepted

#26 21.py
  21.py
Labels: hacktoberfest-accepted

#27 Add Solution for Q28
  Solutions/21-30/28.py
Labels: hacktoberfest-accepted

#29 Adding solution of Problem 45
  Solutions/41-50/45.py
Labels: hacktoberfest-accepted

#30 17th solution
  Solutions/17.py
Labels: hacktoberfest-accepted

#31 Hacktoberfest
  .vscode/settings.json
  Solutions/11-20/11.py
  Solutions/11-20/16.py
Labels: hacktoberfest-accepted

#33 29.py
  Solutions/21-30/29.py
Labels: hacktoberfest-accepted

#34 34.py
  Solutions/31-40/34.py
Labels: hacktoberfest-accepted

#35 42.py
  Solutions/41-50/42.py
Labels: hacktoberfest-accepted

#39 31.py
  Solutions/31-40/31.py
Labels: hacktoberfest-accepted

#40 Problem 16
  16.py
  29.py
Labels: hacktoberfest-accepted

#42 7.py
  Solutions/1-10/7.py
Labels: hacktoberfest-accepted

#49 Solution for Q13
  Solutions/11-20/13.py
  Solutions/11-20/Remaining Ques Nos
Labels: good first issue, hacktoberfest-accepted

#50 added 46 question answer
  Solutions/41-50/46.py
Labels: hacktoberfest-accepted

#52 Created 8.py
  Solutions/1-10/8.py
Labels: hacktoberfest-accepted

#53 Created 33.py
  Solutions/31-40/33.py
Labels: hacktoberfest-accepted

#54 Add thing:
  Solutions/31-40/40.py
  Solutions/31-40/Remaining Ques Nos
  Solutions/41-50/49.py
  Solutions/41-50/Remaining Ques Nos
Labels: hacktoberfest-accepted

#56 Added solution for 40
  Solutions/31-40/40.py
Labels: hacktoberfest-accepted
